version: '3.8'

services:
  autogen-aider:
    image: danum/autogen-aider
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ${MOUNT_SOURCE:-./my-project}
        target: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["python", "main.py"]
